### ISSUE TITLE
Previews crashing when working from a Swift Package (SPM)

### ISSUE THREAD

**Issue by tiagopigatto** [heap/heap-swift-core-sdk#1]
All the previews on our package are broken after we updated to the new heap-swift-core-sdk. See the attached crash image:

![image](https://user-images.githubusercontent.com/2766087/227265891-b67493b7-fe58-4879-bb6a-cbf95bff2b0b.png)

**Comment by bnickel** [comment]
Hi Tiago,

It looks like your app has multiple targets, with SharedFrameworks importing HeapSwiftCore and the app importing SharedFrameworks.

Because HeapSwiftCore is currently configured as a dynamic library, it needs to be included in the "Frameworks and Libraries" section for both Targets:

**SharedFrameworks**

![Screenshot 2023-03-24 at 9 03 34 AM](https://user-images.githubusercontent.com/662837/227581602-3e72af97-ebbc-4a4d-9356-f4604e82cd96.png)

**App**

![Screenshot 2023-03-24 at 9 03 50 AM](https://user-images.githubusercontent.com/662837/227581643-8b4bc2ca-bf6f-41b0-bb47-4b4d676700d4.png)

We are working on a change right now that will fix this in the next release.

**Comment by bnickel** [comment]
Sorry for the late replay, but this was addressed in 0.1.2.  With the new install process, Xcode should automatically include the dependencies from the shared framework.
